services:
    playwright-web-mcp:
        # image: ghcr.io/nchekwa/playwright-web-mpc:latest
        image: playwright-web-mcp
        build:
            context: .
        hostname: playwright-web-mcp
        ports:
            - "6901:6901" # HTTP WEB -> noVNC (set password via VNC_PASSWORD)
            - "8831:8831" # Playwright MCP
            - "8832:8832" # Chrome DevTools MCP (Supergateway)
        # shm_size: '2gb'
        volumes:
            - ./config:/config
        environment:
            - VNC_RESOLUTION=1920x1080
            # - PLAYWRIGHT_VIEWPORT_SIZE=1024,1080
            ## - PLAYWRIGHT_VIEWPORT_SIZE=1920,1080
            # - VNC_PASSWORD=secret
            # - NOVNC_PORT=6901       # docker noVNC internal port
            # - CHROME_DEVTOOLS_MCP_ENABLED=true
            # - CHROME_DEVTOOLS_MCP_PORT=8832
